### ISSUE TITLE
输入密码无反应

### ISSUE THREAD

**Issue by moonbai** [YuKongA/Updater-KMP#26]
https://github.com/user-attachments/assets/68a66bed-aa07-400d-be30-43abb3ed21a6

**Comment by YuKongA** [comment]
貌似是这个小米安全键盘的问题😧

**Comment by moonbai** [comment]
> 貌似是这个小米安全键盘的问题😧

嗯，关闭安全键盘后可以了😰

**Comment by YuKongA** [comment]
> > 貌似是这个小米安全键盘的问题😧
> 
> 嗯，关闭安全键盘后可以了😰

最新的提交可以暂时杜绝这个问题。这应该是 compose 上游的问题。

**Comment by YuKongA** [comment]
该问题已在 CMP 1.7.0-alpha03 中解决
