### ISSUE TITLE
小米社区推送的内测包Updater查不到

### ISSUE THREAD

**Issue by XY50** [YuKongA/Updater-KMP#67]
账号已有内测资格。内测包仅在小米社区推送，Updater查不到
![Screenshot_2024-10-14-23-48-50-163_com xiaomi vipaccount](https://github.com/user-attachments/assets/8d45c568-c233-4ebb-a3e3-99eccea3babf)
![Screenshot_2024-10-14-23-49-12-782_top yukonga updater kmp](https://github.com/user-attachments/assets/99ebac3e-f427-43e1-a3da-d2306cfc2667)
希望可以查询小米社区推送的内测包

**Comment by YuKongA** [comment]
### 用小米社区接口查询会封号

**Comment by XY50** [comment]
哦
