### ISSUE TITLE
为什么不支持查询构建版本

### ISSUE THREAD

**Issue by Afly-dream** [YuKongA/Updater-KMP#75]
miota之前就挂了，现在2.0都出来了，能不能寻找一下其他的解决方案。。。。。

**Comment by YuKongA** [comment]
就算真有办法，现在也不会放公开软件上啊，到时候肯定又堵上了

**Comment by Afly-dream** [comment]
> 就算真有办法，现在也不会放公开软件上啊，到时候肯定又堵上了

em，要不就先做出来，不放肆宣传的话应该不会堵的太快的
