### ISSUE TITLE
显示错误

### ISSUE THREAD

**Issue by Heimaojingzhang888** [YuKongA/Updater-KMP#87]
显示错误，应为MIUI12
![Screenshot_2024-11-30-14-26-38-772_top yukonga updater kmp-edit](https://github.com/user-attachments/assets/f1719b5f-0bae-41d4-b011-629d34650485)

**Comment by YuKongA** [comment]
![image](https://github.com/user-attachments/assets/7fb7f5c7-50ff-49be-9d51-24c01daac911)

奇怪，我这里正常

**Comment by YuKongA** [comment]
好的，我改一下

**Comment by Heimaojingzhang888** [comment]
麻烦了，感谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月30日 16:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [YuKongA/Updater-KMP] 显示错误 (Issue #87) |

Closed #87 as completed.
