### ISSUE TITLE
[建议]添加历史记录

### ISSUE THREAD

**Issue by whx9986** [YuKongA/Updater-KMP#89]
建议在设备名称下方添加一个最近查询过的机型名称，这样多个手机查询时，不必删除设备名称然后再次输入查询，可以方便许多。
![Screenshot_2024-12-03-12-54-05-581_top yukonga updater kmp-edit](https://github.com/user-attachments/assets/8944d8dc-d111-444e-a8fb-0ac3fca9493c)

**Comment by YuKongA** [comment]
后续看情况吧，我自己目前没有这个需求

**Comment by YuKongA** [comment]
![1e95268d514f8193e6d920ed8c67d6eb](https://github.com/user-attachments/assets/3ef72f42-e788-49ca-a3b3-04a65773365e)

已支持
